# Generated by Django 4.2.13 on 2024-06-05 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Loans', '0001_initial'),
        ('Payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLoanDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Loans.loan')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to='Payments.payment')),
            ],
        ),
    ]
